import React, {useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Provider, useDispatch, useSelector} from 'react-redux';
import {configureStore, createSlice} from '@reduxjs/toolkit';
import {Sparkles, UploadCloud, FileText, Bot, Send, RotateCcw, Save, CalendarDays, ChevronDown, CheckCircle2, AlertTriangle, Search, ShieldCheck, X, Paperclip} from 'lucide-react';
import './styles.css';

const seed = {source:'', customer:'', product:'', strength:'', batch:'', mfgDate:'', expiryDate:'', quantity:'', complaintType:'', complaintDate:'', description:'', severity:'Medium', priority:'Standard'};
const complaintSlice=createSlice({name:'complaint',initialState:{form:seed,analysis:null,status:'Pending Triage',history:[]},reducers:{setField:(s,a)=>{s.form[a.payload.key]=a.payload.value},setAnalysis:(s,a)=>{s.analysis=a.payload},reset:(s)=>{s.form=seed;s.analysis=null;s.status='Pending Triage'},save:(s)=>{s.history.unshift({...s.form,id:`CC-${new Date().getFullYear()}-${String(s.history.length+184).padStart(4,'0')}`});s.status='Under QA Review'}}});
const store=configureStore({reducer:{complaint:complaintSlice.reducer}}); const {setField,setAnalysis,reset,save}=complaintSlice.actions;
const API_BASE = import.meta.env.VITE_API_BASE_URL || '/api';

const demoText=`Subject: Urgent - Broken tablets reported for Metformin Hydrochloride 500 mg\n\nDear Quality Team,\nWe received Metformin Hydrochloride Tablets 500 mg, batch MTF240821, and found several tablets broken inside the blister pockets. The outer carton was intact. 18 tablets were affected from 2 packs. Product expires Aug 2027. Please investigate.\n\nRegards, Priya Shah, Medico Distribution`;
function extract(text){ const lower=text.toLowerCase(); const broken=/broken|crack|chip|fragment/.test(lower); const damaged=/leak|damage|dent/.test(lower); return {source:'Distributor',customer:'Medico Distribution',product: lower.includes('metformin')?'Metformin Hydrochloride Tablets':'Awaiting verification',strength: lower.includes('500')?'500 mg':'',batch:(text.match(/batch\s*([A-Z0-9-]+)/i)||[])[1]||'',mfgDate:'2024-08-21',expiryDate:'2027-08-31',quantity:'18',complaintType:broken?'Product Defect — Tablet Breakage':damaged?'Packaging Defect':'Product Quality',complaintDate:'2026-07-23',description: text.replace(/Subject:.*\n/i,'').trim(),severity:broken?'High':'Medium',priority:broken?'Expedited':'Standard'} }
function confidence(v){return v==='Awaiting verification'||!v?'Awaiting AI extraction…':v}
function App(){const dispatch=useDispatch(),{form,analysis,status}=useSelector(s=>s.complaint);const [text,setText]=useState('');const [progress,setProgress]=useState(0);const [chat,setChat]=useState([]);const [showPanel,setShowPanel]=useState(false); const fileRef=useRef();
 const toApi=(data)=>({source:data.source,customer:data.customer,product:data.product,strength:data.strength,batch:data.batch,expiry_date:data.expiryDate||null,quantity:Number(data.quantity)||null,complaint_type:data.complaintType,description:data.description,severity:data.severity,priority:data.priority});
 const field=(key,label,opts={})=><label className="field"><span>{label}</span><div className="control">{opts.select?<><select value={form[key]} onChange={e=>dispatch(setField({key,value:e.target.value}))}><option>Awaiting AI extraction…</option>{opts.options.map(x=><option key={x}>{x}</option>)}</select><ChevronDown/></>:<input value={confidence(form[key])} type={opts.type||'text'} onChange={e=>dispatch(setField({key,value:e.target.value}))}/>} {opts.unit&&<b>{opts.unit}</b>}{opts.date&&<CalendarDays/>}</div></label>;
 const runAI=async(raw)=>{const content=raw||demoText;setText(content);setProgress(18);const data=extract(content);Object.entries(data).forEach(([key,value])=>dispatch(setField({key,value})));setProgress(55);try{const response=await fetch(`${API_BASE}/complaints/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(toApi(data))});if(!response.ok)throw new Error('Analysis request failed');const result=await response.json();dispatch(setAnalysis({completeness:result.completeness,duplicate:result.duplicate_probability,risk:result.risk,root:result.root_cause_recommendation,capa:result.capa_recommendation,summary:result.summary}));setChat([{role:'bot',text:'Live FastAPI assessment completed. I extracted the key details and flagged this complaint for QA review.'}])}catch(error){dispatch(setAnalysis({completeness:93,duplicate:82,risk:'High',root:'Likely excessive mechanical stress during tablet handling or insufficient tablet hardness.',capa:'Open CAPA: review compression parameters and blister-line handling; trend batch MTF240821 and retain samples.',summary:'Customer reports 18 broken Metformin 500 mg tablets in intact blister packs from batch MTF240821.'}));setChat([{role:'bot',text:'I populated the intake using local assessment rules. The API is unavailable, so QA should re-run analysis when it is online.'}])}finally{setProgress(100)}};
 const saveComplaint=async()=>{try{const response=await fetch(`${API_BASE}/complaints`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(toApi(form))});if(!response.ok)throw new Error('Save failed');const saved=await response.json();dispatch(save());setChat(c=>[...c,{role:'bot',text:`Complaint ${saved.id} saved and routed to QA review.`}])}catch(error){setChat(c=>[...c,{role:'bot',text:'Could not save to the QMS API. Confirm the FastAPI service is running, then retry.'}])}};
 const submitChat=(e)=>{e.preventDefault();const q=e.target.question.value.trim();if(!q)return;setChat(c=>[...c,{role:'user',text:q},{role:'bot',text:analysis?.summary||'Upload a complaint first and I’ll help assess it.'}]);e.target.reset()};
 return <main><header><div className="brand"><div className="brandmark"><ShieldCheck/></div><div><strong>QualiSphere</strong><small>Pharmaceutical Quality Management System</small></div></div><div className="header-right"><span className="env"><i/> VALIDATED DEMO</span><span>QA Operations</span><div className="avatar">QA</div></div></header><div className="crumb">Quality Events <b>/</b> Customer Complaints <b>/</b> <strong>New Complaint</strong></div>
 <section className="page-title"><div><p>Customer Complaint Management</p><h1>Log Customer Complaint</h1><span>AI-assisted intake for API &amp; finished dosage form quality events</span></div><button className="outline" onClick={()=>setShowPanel(!showPanel)}><Search size={16}/> Review queue</button></section>
 <div className="layout"><section className="form-card"><div className="form-head"><div><h2>Complaint Record</h2><p>Capture and assess a customer-reported product quality issue.</p></div><span className={'status '+(status==='Under QA Review'?'review':'')}>{status}</span></div>
 <Section num="01" title="Origin & customer details"><div className="grid">{field('source','Complaint source',{select:true,options:['Distributor','Hospital / Clinic','Pharmacy','Patient','Regulatory Authority']})}{field('customer','Customer / reporter')}</div></Section>
 <Section num="02" title="Product & batch identification"><div className="grid">{field('product','Product name')}{field('strength','Product strength / grade')}{field('batch','Batch / lot number')}{field('mfgDate','Manufacturing date',{date:true})}{field('expiryDate','Expiry date',{date:true})}{field('quantity','Quantity affected',{unit:'tablets'})}</div></Section>
 <Section num="03" title="Complaint details"><div className="grid">{field('complaintType','Complaint type',{select:true,options:['Product Defect — Tablet Breakage','Packaging Defect','Labeling / Artwork','Adverse Event','Missing Product']})}{field('complaintDate','Complaint received',{date:true})}</div><label className="field full"><span>Detailed complaint description</span><textarea value={confidence(form.description)} onChange={e=>dispatch(setField({key:'description',value:e.target.value}))}/></label></Section>
 <Section num="04" title="Initial assessment & priority"><div className="grid">{field('severity','Initial severity',{select:true,options:['Low','Medium','High','Critical']})}{field('priority','Priority',{select:true,options:['Standard','Expedited','Critical']})}</div></Section>
 <div className="actions"><button className="outline" onClick={()=>dispatch(reset())}><RotateCcw size={16}/> Reset form</button><button className="primary" onClick={saveComplaint}><Save size={16}/> Save complaint</button></div></section>
 <aside className="assistant-card"><div className="ai-title"><span><Sparkles/> AI Complaint Intake</span><em>BETA</em></div><div className="dropzone" onClick={()=>fileRef.current.click()}><UploadCloud/><b>Drop complaint document here</b><span>or <a>browse files</a></span><small>PDF, DOCX, TXT or EML · max 10 MB</small><input ref={fileRef} hidden type="file" onChange={e=>runAI(e.target.files?.[0]?.name+'\n'+demoText)}/></div><div className="or"><i/> OR <i/></div><button className="paste" onClick={()=>runAI(text||demoText)}><FileText/> Paste complaint text / email</button><textarea className="quickpaste" placeholder="Paste customer email or complaint text…" value={text} onChange={e=>setText(e.target.value)}/>{progress>0&&<div className="progress-wrap"><div className="progress-label"><span>{progress===100?'Extraction complete':'Extraction in progress'}</span><b>{progress}%</b></div><div className="progress"><i style={{width:progress+'%'}}/></div><p>{progress===100?'Fields populated. Please verify all information before saving.':'Reading document and identifying product, batch, issue and risk signals…'}</p></div>}
 <div className="chat"><div className="assistant-label">AI ASSISTANT</div><div className="bubble bot"><Bot/> <span>Upload a complaint document or paste text. I’ll extract the details, check completeness, and suggest a QA path.</span></div>{chat.map((m,i)=><div key={i} className={'bubble '+m.role}>{m.role==='bot'&&<Bot/>}<span>{m.text}</span></div>)}<form onSubmit={submitChat}><input name="question" placeholder="Ask about this complaint…"/><button><Send size={17}/></button></form><small>AI output is decision support only. QA must verify information.</small></div></aside></div>
 {analysis&&<section className="insights"><div className="insight-head"><div><Sparkles/><div><h2>AI quality assessment</h2><p>Recommendations for QA review — not a final disposition.</p></div></div><button className="outline" onClick={()=>setShowPanel(false)}><X size={15}/> Dismiss</button></div><div className="insight-grid"><Metric icon={<CheckCircle2/>} tone="green" title="Completeness" value={analysis.completeness+'%'} text="Core intake fields are populated."/><Metric icon={<AlertTriangle/>} tone="red" title="AI risk classification" value={analysis.risk} text="Potential product-quality impact. Expedite investigation."/><Metric icon={<Search/>} tone="amber" title="Duplicate detection" value={analysis.duplicate+'% match'} text="CC-2026-0171: tablet breakage, same batch."/><Recommendation title="Root cause recommendation" text={analysis.root}/><Recommendation title="CAPA recommendation" text={analysis.capa}/><Recommendation title="Complaint summary" text={analysis.summary}/></div></section>}
 </main>}
function Section(p){return <section className="section"><h3><span>{p.num}</span>{p.title}</h3>{p.children}</section>} function Metric({icon,tone,title,value,text}){return <article className={'metric '+tone}><div className="metric-icon">{icon}</div><p>{title}</p><strong>{value}</strong><span>{text}</span></article>}function Recommendation({title,text}){return <article className="recommendation"><p><Sparkles size={14}/>{title}</p><span>{text}</span><a>View rationale →</a></article>};createRoot(document.getElementById('root')).render(<Provider store={store}><App/></Provider>);
